window.quotes = [
  { text: "Endast en gentleman äter röv", author: "Jerry", watershed: true },
  { text: "Jag gillar inte saker som rimmar på bajs", author: "Jens Jacobsen", watershed: false },
  { text: "De ska ge dig för mycket fjong", author: "Tova Westerlund", watershed: false },
  { text: "Kenth har bönor i sin snusdosa!", author: "Fabian Olsson", watershed: false },
  { text: "This IS the biggest one!", author: "Max Sjöstrand", watershed: false },
  { text: "Varje gång en utvecklare säger 'ingen stress' gråter en projektledare", author: "Alexander Boman Skoug", watershed: false },
  { text: "6 liter eller inget!", author: "Alexander Boman Skoug", watershed: false },
  { text: "Det är inte kul att bli slagen, bara att bli skjuten", author: "Fabian Olsson", watershed: false },
  { text: "Får ni också känslan av att vi bara sitter är & leker vuxna?", author: "Tova Westerlund", watershed: false },
  { text: "Leverera - att få lever strösslad över sin måltid (oftast av Max)", author: "Okänd", watershed: false },
  { text: "Där e´ datajux jahh...", author: "Cecil Folkessson", watershed: false },
  { text: "Vi har ett ordspråk, sparka på den Fabian som ligger ner", author: "Daniel Andersen", watershed: false },
  { text: "Jens, vad va det du sa om hemmorroider", author: "Alexander Boman Skoug", watershed: false },
  { text: "Ta det lungt, jag är snart medicinerad", author: "Jens Jacobsen", watershed: false },
  { text: "Man får säga snopp även om HR är med", author: "Emma Rask (HR)", watershed: false },
  { text: "Sålt smöret och tappat det igen", author: "Max Sjöstrand", watershed: false },
  { text: "O så kommer den där hudfärgade köttgrejen", author: "Jacob", watershed: true },
  { text: "Jag behöver inga agenter jag har bara skills", author: "Rix", watershed: false },
  { text: "Det är bara att pressa mot munnen och svälja", author: "Pontus Vigstrand", watershed: true },
  { text: "Det är inte säkert att bibeln är 100% rätt", author: "Simon Jackler", watershed: false },
  { text: "Är hans fru singel?", author: "Alexander Boman Skoug", watershed: false },
  { text: "I might be an idiot... I am an idiot!", author: "Marcus Ekelund", watershed: false },
];
